In [3]:
!pip install mlxtend

In [4]:
data = [
    ['A','B','C','D'],
    ['A','B','C','E'],
    ['B','C'],
    ['B','E']
]
print(type(data))
print(data)

<class 'list'>
[['A', 'B', 'C', 'D'], ['A', 'B', 'C', 'E'], ['B', 'C'], ['B', 'E']]


In [5]:
from mlxtend.preprocessing import TransactionEncoder

TE = TransactionEncoder()
X = TE.fit(data)
print(X)

TDB = TE.fit(data).transform(data)

print(type(TDB))
print(TDB)

TransactionEncoder()
<class 'numpy.ndarray'>
[[ True  True  True  True False]
 [ True  True  True False  True]
 [False  True  True False False]
 [False  True False False  True]]


In [7]:
Item_list = TE.columns_
print(type(Item_list))
print(Item_list)

<class 'list'>
['A', 'B', 'C', 'D', 'E']


In [8]:
DB = TDB.astype("int")
print(type(DB))
print(DB)

<class 'numpy.ndarray'>
[[1 1 1 1 0]
 [1 1 1 0 1]
 [0 1 1 0 0]
 [0 1 0 0 1]]


In [9]:
import pandas as pd

df = pd.DataFrame(DB, columns = Item_list)

print(df)


   A  B  C  D  E
0  1  1  1  1  0
1  1  1  1  0  1
2  0  1  1  0  0
3  0  1  0  0  1


In [10]:
from mlxtend.frequent_patterns import apriori

frequent_item = apriori(df, min_support=0.5, use_colnames=True)

print(frequent_item)

   support   itemsets
0     0.50        (A)
1     1.00        (B)
2     0.75        (C)
3     0.50        (E)
4     0.50     (B, A)
5     0.50     (C, A)
6     0.75     (B, C)
7     0.50     (B, E)
8     0.50  (B, C, A)


In [13]:
from mlxtend.frequent_patterns import association_rules

rule = association_rules(frequent_item, metric="confidence", min_threshold=0.6)

print(rule)
rule.to_csv("Rule.csv")

   antecedents consequents  antecedent support  ...  leverage  conviction  zhangs_metric
0          (A)         (B)                0.50  ...     0.000         inf            0.0
1          (C)         (A)                0.75  ...     0.125         1.5            1.0
2          (A)         (C)                0.50  ...     0.125         inf            0.5
3          (B)         (C)                1.00  ...     0.000         1.0            0.0
4          (C)         (B)                0.75  ...     0.000         inf            0.0
5          (E)         (B)                0.50  ...     0.000         inf            0.0
6       (B, C)         (A)                0.75  ...     0.125         1.5            1.0
7       (B, A)         (C)                0.50  ...     0.125         inf            0.5
8       (A, C)         (B)                0.50  ...     0.000         inf            0.0
9          (C)      (B, A)                0.75  ...     0.125         1.5            1.0
10         (A)      (